# Generated by Django 4.2.1 on 2023-06-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/user_profiles/avatar7.png', null=True, upload_to='images/user_profiles'),
        ),
    ]
